name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm install --package-lock # 相当于npm install
    - run: npm run docs:build

    #发布到matf5.github.io
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository-name: matf5/matt-blog #可以新建一个mybells.github.io仓库发布到master
        branch: gh-pages
        folder: docs/.vuepress/dist
